#!/bin/bash

##############################################
## dwm popup to choose between open windows ##
## does not change to respective monitor    ##
##############################################

# Date format, for use as the prompt.
date=$(date +"%a %d. %b %R")

# dmenu cannot display more than 30 lines, to avoid screen clutter. Only relevant if you have more than 30 windows open.
height=$(wmctrl -l | wc -l)
if [[ $height -gt 30 ]]; then
	heightfit=30
else
	heightfit=$height
fi

num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' | dmenu -b -i -p "$date" -l $heightfit | cut -d '-' -f -1)
[[ -z "$num" ]] && exit

WID=$(wmctrl -l | sed -n "$num p" | cut -c -10)
echo "focus target $WID"

if ! [ -e ~/paperbenni/ismultimonitor ]; then
	wmctrl -i -a "$WID"
	exit
else
	echo "multi monitor setup detected"
	OLDID=$(xprop -root | head -1 | grep -o '0x.*' | sed 's/0x/0x0/')
	wmctrl -i -a "$WID"
fi

NEWID=$(xprop -root | head -1 | grep -o '0x.*' | sed 's/0x/0x0/')

if ! [ "$NEWID" = "$WID" ]; then
	xdotool key "super+Tab"
	xdotool key "super+comma"
	wmctrl -i -a "$WID"
else
	xdotool key "super+comma"
	NEWERID=$(xprop -root | head -1 | grep -o '0x.*' | sed 's/0x/0x0/')
	if ! [ "$NEWERID" = "$OLDID" ]; then
		xdotool key "super+Tab"
	fi
	xdotool key "super+comma"
fi
