#!/bin/bash

if ping -c 1 google.com; then
    if [ -z "$@" ]; then
        curl -s https://raw.githubusercontent.com/instantos/instantos/master/install.sh | sudo bash 2>&1 | tee ~/instantosinstall.log
    else
        curl -s https://raw.githubusercontent.com/instantos/instantos/master/install.sh | sudo bash -s $@ 2>&1 | tee ~/instantosinstall.log
    fi
fi
