#!/bin/bash

##############################################
## dwm popup to choose between open windows ##
## does not change to respective monitor    ##
##############################################

if ! [ -n "$1" ]; then
  
    num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' | dmenu -b -i | cut -d '-' -f -1)
    [[ -z "$num" ]] && exit

    WID=$(wmctrl -l | sed -n "$num p" | cut -c -10)
else
    WID="$1"
fi

echo "focus target $WID"

focuswin() {
    [[ $1 =~ "," ]] && echo "error focussing" && return 1
    wmctrl -i -a "$1"
}

if ! [ -e ~/paperbenni/ismultimonitor ]; then
    focuswin "$WID"
    echo "exiting"
    exit
fi

getmonitor() {
    XPOS=$(xdotool getwindowfocus getwindowgeometry | grep -Eoi 'position.*,' | grep -o '[0-9]*')
    if [ "$XPOS" -gt "1919" ]; then
        echo "1"
    else
        echo "0"
    fi
}

[ "$(pfw)" = "$WID" ] && exit
OLD="$(pfw)"
OLDM="$(getmonitor)"

focuswin "$WID"

if ! [ "$(pfw)" = "$WID" ]; then
    if ! [ "$OLDM" = "$(getmonitor)" ]; then
        xdotool key 'super+comma'
    fi
    [ "$OLD" = "0x000001e1" ] || focuswin "$OLD"
    xdotool key 'super+comma'
    focuswin "$WID"
else
    if ! [ "$OLDM" = "$(getmonitor)" ]; then
        xdotool key 'super+comma'
        [ "$OLD" = "0x000001e1" ] || focuswin "$OLD"
        xdotool key 'super+comma'

    fi
fi
