#!/usr/bin/dash

# wallpaper setter wrapper to support rox icons

VARTIMES="$(xrandr | grep '[^s]connected.*x' | wc -l)"
if [ "$VARTIMES" -gt 1 ]; then
    echo "settings wallpaper for $VARTIMES monitors"
    for i in $(seq 0 "$((VARTIMES - 1))"); do
        echo "i $i"
        nitrogen --set-scaled --save --head="$i" "$1"
    done
else
    echo "settings wallpaper for one monitor"
    nitrogen --set-scaled --save "$1"
fi

# set wallpaper for ROX
if [ -e ~/.config/rox.sourceforge.net ]; then
    ROXFILE="$(realpath ~/.config/rox.sourceforge.net/ROX-Filer/pb_Default)"

    #initialize with default file
    if ! [ -e "$ROXFILE" ]; then
        echo '<?xml version="1.0"?>
<pinboard>
  <backdrop style="Tiled">'"$HOME"'/Pictures/instantwallpaper.png</backdrop>
  <icon x="32" y="32" label="Home">'"$HOME"'</icon>
</pinboard>' >"$ROXFILE"
    fi

    if grep -q '<backdrop' "$ROXFILE"; then
        sed -i '/<backdrop /d' "$ROXFILE"
    fi

    sed -i "/<pinboard/a<backdrop style=\"Tiled\">$(realpath $1)</backdrop>" "$ROXFILE"

fi

if pgrep ROX >/dev/null 2>&1; then
    pkill ROX
    if ! pgrep ROX; then
        rox --pinboard Default
    fi
fi
