#!/bin/bash

if ! albert show
then
    if [ -e ~/.config/albert/albert.conf ]
    then
        sed -i 's/^theme=.*/theme=Arc Dark Blue/g' ~/.config/albert/albert.conf
    fi
    notify-send 'starting albert'
    albert &
    sleep 5
    albert show
fi
