#!/bin/bash

# upgrade instantOS to the next version

if whoami | grep -q '^root$'; then
    echo "please do not run instantupdate as root"
    exit 1
fi
if ! checkinternet; then
    echo "internet is required to upgrade instantOS"
    exit 1
fi

if ! grep -q '^[^#]' /etc/pacman.d/mirrorlist; then
    if echo 'your mirrorlist seems to be broken
yould you like to repair it?
leaving it in this state might leave you unable to update' | imenu -C; then
        sudo tee /etc/pacman.d/mirrorlist </usr/share/instantdotfiles/examplemirrors
    fi
fi

sudo pacman -Sy --noconfirm

instantshell
sudo pacman -Syuu --noconfirm
command -v yay && yay
instantdotfiles

if ! iconf -i notheming; then
    instantthemes a arc
fi

sudo bash /usr/share/instantutils/rootinstall.sh
sudo bash /usr/share/instantdotfiles/rootinstall.sh
bash /usr/share/instantdotfiles/userinstall.sh

if ! command -v pacdiff; then
    sudo pacman -S --noconfirm pacman-contrib
fi

if grep '..' /etc/pacman.d/mirrorlist | grep -v '^#' | grep -q '..'; then
    echo "mirrors found"
else
    echo "mirrors have been cleared"
    cat /usr/share/instantdotfiles/examplemirrors | sudo tee /etc/pacman.d/mirrorlist
fi
