#!/usr/bin/dash
# slop wrapper that puts out a format readable by instantwm
# looks different if you have compositing

if pgrep picom > /dev/null; then
    slop --highlight -b 3 -c 0.3203125,0.875,0.40234375,0.1 $@
else
    slop -b 3 -c 0.3203125,0.875,0.40234375 $@
fi
