#!/bin/bash

# Show a list of available key bindings

dlbinds() {
    if ping -c 1 archlinux.org; then
        curl -s 'https://raw.githubusercontent.com/instantOS/instantos.github.io/master/youtube/hotkeys.md' |
            sed 's/^\([^|#]\)/    \1/g' |
            sed 's/^##*[ ]*/ /g' >~/.cache/instantos/hotkeys.md
    fi
}

if ! [ -e ~/.cache/instantos/hotkeys.md ]; then
    mkdir -p ~/.cache/instantos
    dlbinds
fi

cat ~/.cache/instantos/hotkeys.md >/tmp/hotkeys
dlbinds &

less --mouse --wheel-lines=3 /tmp/hotkeys
