#!/bin/bash

# Show a list of available key bindings

dlbinds() {
    curl -s 'https://raw.githubusercontent.com/instantOS/instantos.github.io/master/youtube/hotkeys.md' |
        sed 's/^\([^|#]\)/    \1/g' |
        sed 's/^##*[ ]*/ /g' >~/.cache/instantos/hotkeys.md &
}

if ! [ -e ~/.cache/instantos/hotkeys.md ]; then
    mkdir -p ~/.cache/instantos &>/dev/null
    dlbinds
fi

cat ~/.cache/instantos/hotkeys.md >/tmp/hotkeys
dlbinds &
less --mouse --wheel-lines=3 /tmp/hotkeys
