#!/bin/bash

# instantmenu wrapper to be used as $SUDO_ASKPASS

if [ -n "$PASSPROMPT" ]; then
    PROMPT="$PASSPROMPT"
else
    PROMPT="enter password"
fi

PASSWORD="$(echo '' | instantmenu -c -bw 4 -p "   $PROMPT  " -P -h -1)"
echo "$PASSWORD"
