#!/bin/bash
# show notification history in rofi
# x to mark as readentry headerentry headerentry headerentry headerentry headerentry header
# esc to exit

[ -e /tmp/notifications ] || mkdir /tmp/notifications
cd /tmp/notifications

[ -e notif.txt ] && grep -q '....' <notif.txt || exit

NREAD=$(tac notif.txt | rofi -dmenu -i -p notifications -kb-accept-entry 'Alt+x' -markup-rows)

while [ -n "$NREAD" ]; do
    grep -vF "$NREAD" notif.txt >tmp.notif && mv tmp.notif notif.txt
    NREAD=$(tac notif.txt | rofi -dmenu -i -p notifications -kb-accept-entry 'Alt+x' -markup-rows)
done
