#!/usr/bin/env bash

# simple clipmenu wrapper

: "${CM_DIR="${XDG_RUNTIME_DIR-"${TMPDIR-/tmp}"}"}"
major_version=6

if ! pgrep -f clipmenud; then
    clipmenud
fi &

shopt -s nullglob

cache_dir=$CM_DIR/clipmenu.$major_version.$USER
cache_file=$cache_dir/line_cache

if [ "$1" = "delete" ]; then
    if imenu -c "clear clipboard cache?"; then
        echo "clearing cache"
        echo "cache $cache_file"
        echo "cleared" >"$cache_file"
        exit
    fi
fi

CM_LAUNCHER=instantmenu clipmenu -p "    " -q 'clipboard manager' -h -1 -lc "instantclipmenu delete"
