#!/bin/bash

# really simple file picker using fd, kitty and fzf

if [ -z "$INSTANTFILECOMMAND" ]; then
    export FZF_DEFAULT_COMMAND='fd --type file'
else
    export FZF_DEFAULT_COMMAND="$INSTANTFILECOMMAND"
fi

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

if [ -z "$INSTANTFILECLI" ]; then
    if command -v kitty >/dev/null 2>&1; then
        kitty --class instantfloat -e bash -c 'fzf > /tmp/instantfilepickchoice' &>/dev/null
    else
        fzf >/tmp/instantfilepickchoice
    fi
else
    fzf >/tmp/instantfilepickchoice
fi

CHOICE="$(cat /tmp/instantfilepickchoice)"

rm /tmp/instantfilepickchoice

if [ -n "$CHOICE" ] && [ -e "$CHOICE" ]; then
    echo "$CHOICE"
else
    exit 1
fi
