#!/bin/bash

if ! checkinternet; then
    echo "internet is required to upgrade instantOS"
    exit 1
fi

curl -s "https://raw.githubusercontent.com/instantOS/iso-profiles/master/pacclear.sh" | sudo bash
sudo pacman -Sy --noconfirm

instantshell
sudo pacman -Syuu --noconfirm
instantdotfiles -f
instantthemes a arc

sudo bash /usr/share/instantutils/rootinstall.sh
sudo bash /usr/share/instantdotfiles/rootinstall.sh
bash /usr/share/instantdotfiles/userinstall.sh
