#!/bin/bash

## instantmenu speedtest wrapper

instantinstall speedtest-cli || exit 1

imenu -w "running speedtest, please wait" &
SPEEDOUT="$(speedtest-cli --simple)"
pkill instantmenu

if [ -z "$SPEEDOUT" ]; then
    echo 'running the speedtest failed
are you connected to the internet?' | imenu -M
    exit 1
fi

PING="$(sed -n '1p' <<<"$SPEEDOUT" | grep -o '[0-9].*')"
DOWNLOAD="$(sed -n '2p' <<<"$SPEEDOUT" | grep -o '[0-9].*')"
UPLOAD="$(sed -n '3p' <<<"$SPEEDOUT" | grep -o '[0-9].*')"

[ -e ~/.cache/instantos/speedtest ] || touch ~/.cache/instantos/speedtest
sed -i "1i$(date '+%Y.%m.%d.%H.%M'):$PING:$DOWNLOAD:$UPLOAD" ~/.cache/instantos/speedtest
sed -i '400,$d' ~/.cache/instantos/speedtest

while :; do
    CHOICE="$(
        {
            echo "{blue icon=speedometer} $PING"
            echo "{blue icon=download} $DOWNLOAD"
            echo "{blue icon=upload} $UPLOAD"
            echo "{blue icon=content-copy} Copy all"
            echo "OK"
        } | instantmenu \
            --lines 20 \
            --position center \
            --line-height auto \
            --managed \
            --width auto \
            --placeholder 'speedtest'
    )"

    [ -z "$CHOICE" ] && exit 1

    if [ "$CHOICE" = "OK" ]; then
        exit
    fi

    if [ "$CHOICE" = "$PING" ]; then
        COPIER="$PING"
    elif [ "$CHOICE" = "$DOWNLOAD" ]; then
        COPIER="$DOWNLOAD"
    elif [ "$CHOICE" = "$UPLOAD" ]; then
        COPIER="$UPLOAD"
    elif [ "$CHOICE" = "Copy all" ]; then
        COPIER="$PING
Download: $DOWNLOAD
Upload: $UPLOAD"
    fi

    [ -n "$COPIER" ] && echo "$COPIER" | xclip -selection c && notify-send "copied $COPIER to clipboard"

done
