#!/bin/bash

# instantmenu wrapper to be used as $SUDO_ASKPASS

if [ -n "$PASSPROMPT" ]; then
    PROMPT="$PASSPROMPT"
else
    PROMPT="enter password"
fi

PASSWORD="$(echo '' | instantmenu --position center --border-width 4 -p "   $PROMPT  " --password --line-height -1)"
echo "$PASSWORD"
