#!/usr/bin/dash

# first time help message when opening the terminal

echo "> Welcome
> instantOS is using the kitty terminal emulator and tmux terminal multiplexer
> Because of this, some things work differently
> selecting text is done with Shift + Left mouse button
> Copy Paste is Ctrl + Shift + C/V
> Font size is set with Ctrl + +/-
> Configuration is done through ~/.config/kitty/kitty.conf
OK
Don't show again" | imenu cli -l "quick info" >/tmp/helpmsg

if grep '^Don' /tmp/helpmsg; then
    sed -i 's/.*instantterminalhelp.*//g' ~/.zshrc
    iconf -i nohelp 1
fi
