#!/bin/bash

# tool to run instantARCH modules from a normal installation

if ! [ -e ~/.cache/instantos/instantarch ]; then
    echo "fetching instantarch"
    notify-send "fetching instantarch"
    mkdir -p ~/.cache/instantos
    cd ~/.cache/instantos || exit 1
    git clone --depth=1 'https://github.com/instantos/instantarch'
fi

instantinstall ripgrep

cd ~/.cache/instantos/instantarch || exit 1
git pull

[ -e ~/.cache/instantos/iroot ] && mkdir -p ~/.cache/instantos/iroot
IROOT="$(realpath ~/.cache/instantos/iroot)"
INSTANTARCH="$(realpath ~/.cache/instantos/instantarch)"
export INSTANTARCH
export IROOT

if [ -z "$1" ]; then
    echo "usage: instantarchrun ask/run modulename"
fi

if [ "$1" = "ask" ]; then
    if [ -z "$2" ]; then
        echo "usage: instantarchrun ask questionname"
    fi
    if ! rg "$2()" "$INSTANTARCH"/; then
        echo "question $2 not found"
        exit 1
    fi
    echo "asking instantarch question"
    bash -c "source $INSTANTARCH/askutils.sh && $2"
elif [ "$1" = "run" ]; then
    echo "running instantarch module"
    if [ -z "$2" ]; then
        echo "usage: instantarchrun run modulename"
        exit 1
    fi
    if ! [ -e "$INSTANTARCH/$2.sh" ]; then
        echo "question $2 not found"
        exit 1
    fi
    instantsudo bash -c "cd /root/instantARCH && git reset --hard && git pull && ./$2"
fi
