#!/bin/bash

# basic menu activated from the top left

CHOICE="$(echo ':b Applications
:b Settings
:b Terminal
:b Info
:g Documentation
:g Keybinds
:r Shutdown
:r Close menu' | instantmenu -i --border-width 4 -w -1 --line-height -1 -n -l 10 -x 0 --match-mode dmenu -a 0)"

[ -z "$CHOICE" ] && exit

echo "$CHOICE"
case "$CHOICE" in
    *Applications)
        sleep 0.05
        appmenu &
        ;;
    *Keybinds)
        ins keyhelp --gui &
        ;;
    *Settings)
        ins settings --gui &
        ;;
    *Info)
        kitty -e sh -c 'fastfetch && echo -ne "$(cat /usr/share/instantutils/thanks.txt | sed "s/^/   /g")" && sleep 60m' &
        ;;
    *Shutdown)
        instantshutdown &
        ;;
    *Terminal)
        kitty &
        ;;
    *Documentation)
        xdg-open 'https://instantos.io/docs/' &
        ;;
    *menu)
        echo "closed menu"
        ;;
    *)
        echo "other choice"
        instantmenu_smartrun "startmenu" "$CHOICE"
        ;;
esac

exit
