#!/bin/bash

# replacement for gksudo using instantmenu
if ! sudo -n true 2>/dev/null; then
    PASSWORD=$(echo '' | instantmenu -c -bw 4 -p "   sudo password for $USER  " -P -h -1)

    if [ -z "$PASSWORD" ]; then
        echo "sudo canceled by user"
        exit
    fi

    while ! echo "$PASSWORD" | sudo -S true; do
        PASSWORD=$(echo '' | instantmenu -c -bw 4 -p "     wrong password, enter sudo password for $USER" -P -h -1)
        if [ -z "$PASSWORD" ]; then
            exit
        fi
    done
    echo "$PASSWORD" | sudo -S "$@"
else
    sudo -S "$@"
fi
