#!/bin/bash

CHOICE="$(echo 'applications
settings
terminal
info
shutdown
get started
close menu' | instantmenu -n -l 10 -C -F)"

[ -z "$CHOICE" ] && exit
echo "$CHOICE"
case "$CHOICE" in
applications)
    zenity --info --text="it is recommended to launch applications by clicking in the top right corner instead"
    appmenu &
    ;;
settings)
    instantsettings &
    ;;
info)
    urxvt -e sh -c 'neofetch | less -r' &
    ;;
shutdown)
    instantshutdown &
    ;;
terminal)
    urxvt -cd "$HOME" &
    ;;
close+)
    echo "closed menu"
    ;;
esac
