#!/usr/bin/dash

# first time help message when opening the terminal

echo "{heading} Welcome
{heading} instantOS is using the kitty terminal emulator and tmux terminal multiplexer
{heading} Because of this, some things work differently
{heading} selecting text is done with Shift + Left mouse button
{heading} Copy Paste is Ctrl + Shift + C/V
{heading} Font size is set with Ctrl + +/-
{heading} Configuration is done through ~/.config/kitty/kitty.conf
OK
Don't show again" | imenu cli -l "quick info" >/tmp/helpmsg

if grep '^Don' /tmp/helpmsg; then
    sed -i 's/.*instantterminalhelp.*//g' ~/.zshrc
    iconf -i nohelp 1
fi
