#!/bin/bash

###################################################
## shut down pc and break instantwm restart loop ##
###################################################

answer=$(echo " " | instantmenu -p "do you want to shut down?")

case "$answer" in
y)
    rm ~/.instantosrunning
    sleep 0.4
    shutdown now
    ;;
r)
    rm ~/.instantosrunning
    sleep 0.4
    reboot
    ;;

s)
    rm ~/.instantosrunning
    sleep 0.4
    kill -9 -1
    ;;
*)
    echo "no choice, not shutting down"
    ;;
esac
