#!/bin/bash

# alt-tab application switcher using instantmenu

num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn |
    sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' |
    instantmenu -l 10 -A -c -bw 4 -w 700 -i -p "windows" | cut -d '-' -f -1)
[[ -z "$num" ]] && exit
wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -a
