#!/bin/bash
# show notification history in rofi
# x to mark as read
# esc to exit

[ -e /tmp/notifications ] || mkdir /tmp/notifications
cd /tmp/notifications

[ -e notifications.txt ] && grep -q '....' <notifications.txt || exit

NREAD=$(grep -F -x -v -f read.txt notifications.txt | rofi -dmenu -i -p notifications -kb-accept-entry 'Alt+x' -markup-rows)

while [ -n "$NREAD" ]; do
    sed -i "/$NREAD/d" ./notifications.txt
    NREAD=$(grep -F -x -v -f read.txt notifications.txt | rofi -dmenu -i -p notifications -kb-accept-entry 'Alt+x' -markup-rows)
done
