#!/bin/bash

###############################################
## x session for instantOS, use with lightdm ##
###############################################

# used for shutdown
touch ~/.instantosrunning

# loop so crashing instantwm doesn't end the x session
while test -e ~/.instantosrunning; do
    # Log stderror to a file
    instantwm 2>~/.instantos.log
done
