#!/bin/bash

####################################################
## x session for paperbenni-dwm, use with lightdm ##
####################################################

touch ~/.dwmrunning

while test -e ~/.dwmrunning; do
    # Log stderror to a file
    dwm 2>~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
